<?php

namespace BlogBundle\Repository;

use BlogBundle\Entity\Article;

use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping;
use Doctrine\ORM\OptimisticLockException;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
        public function __construct(EntityManagerInterface $em,
                                     Mapping\ClassMetadata $metadata=null)
    {
        parent::__construct($em,
            $metadata==null ? new Mapping\ClassMetadata(Article::class):$metadata
        );
    }

    /**
     * @param Article $article
     * @return bool
     */
    public function insert(Article $article)
    {

        try {
            $this->_em->persist($article);
            $this->_em->flush();
            return true;
        } catch (OptimisticLockException $e) {
            return false;
        }
    }


    /**
     * @param Article $article
     * @return bool
     */
    public function update(Article $article)
    {

        try {
            $this->_em->merge($article);
            $this->_em->flush();
            return true;
        } catch (OptimisticLockException $e) {
            return false;
        }
    }


}
