<?php

namespace BlogBundle\Repository;

use Doctrine\ORM\ORMException;
use BlogBundle\Entity\User;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping;
use Doctrine\ORM\OptimisticLockException;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function __construct(EntityManagerInterface $em,
                                Mapping\ClassMetadata $metadata=null)
    {
        parent::__construct($em,
            $metadata==null ? new Mapping\ClassMetadata(User::class):$metadata
        );
    }

    public function insert(User $user){

        try {
            $this->_em->persist($user);
            $this->_em->flush();
            return true;
        } catch (OptimisticLockException $e) {
            return false;
        }

    }
    public function update(User $user){

        try {
            $this->_em->merge($user);
            $this->_em->flush();
            return true;
        } catch (OptimisticLockException $e) {
            return false;
        }

    }


}
